kind: pipeline
type: docker
name: build
steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
---
kind: pipeline
type: docker
name: deploy
steps:
- name: greeting
  image: alpine
  commands:
  - echo deploying